### ISSUE TITLE
Bug with Galsim: logging

### ISSUE THREAD

**Issue by jennykim1016** [jennykim1016/SLRealizer#49]
quasar
('X: ', 0.6411, 'Y: ', -0.14480000000000001, 'mag_ratio', 1.5148695842910036, 'sigma', 1.093153)
quasar
('X: ', -0.20669999999999999, 'Y: ', -0.018499999999999999, 'mag_ratio', 0.65259987091164984, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(-1.602771805888984, galsim.radians), 'e1', 0.0763297, 'half_light_radius', 0.0)
quasar
('X: ', -2.5028000000000001, 'Y: ', 0.49380000000000002, 'mag_ratio', 3.1940106648249023, 'sigma', 1.093153)
quasar
('X: ', 0.3256, 'Y: ', -0.073700000000000002, 'mag_ratio', 0.55374697505673409, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(0.1212181954591295, galsim.radians), 'e1', 0.1924864, 'half_light_radius', 0.0)
quasar
('X: ', -0.35880000000000001, 'Y: ', -0.57079999999999997, 'mag_ratio', 4.9226972149053259, 'sigma', 1.093153)
quasar
('X: ', 1.3472999999999999, 'Y: ', 1.3048, 'mag_ratio', 18.981762450963039, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(-0.012370153718532962, galsim.radians), 'e1', 0.22051899999999999, 'half_light_radius', 0.0)
quasar
**('X: ', 2.423, 'Y: ', -0.33629999999999999, 'mag_ratio', 13.725968456475716, 'sigma', 1.093153)
quasar
('X: ', -0.2319, 'Y: ', 0.060699999999999997, 'mag_ratio', 3.989810118999781, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(3.037057903370845, galsim.radians), 'e1', 0.54558580000000001, 'half_light_radius', 0.0)** : RuntimeError: HSM Error: Error: too many iterations in adaptive moments

**Comment by jennykim1016** [comment]
quasar
('X: ', 0.57989999999999997, 'Y: ', -0.62560000000000004, 'mag_ratio', 4.4721298213786014, 'sigma', 1.093153)
quasar
('X: ', -0.29239999999999999, 'Y: ', 0.076100000000000001, 'mag_ratio', 1.2392129485411107, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(1.5749814518082539, galsim.radians), 'e1', 0.46908879999999997, 'half_light_radius', 0.0)
quasar
('X: ', -1.3368, 'Y: ', 0.70820000000000005, 'mag_ratio', 31.371637360291444, 'sigma', 1.093153)
quasar
('X: ', 0.3049, 'Y: ', -0.1724, 'mag_ratio', 5.3131490134739918, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(-2.714451244432213, galsim.radians), 'e1', 0.057200599999999997, 'half_light_radius', 0.0)
quasar
('X: ', -0.43569999999999998, 'Y: ', -0.28599999999999998, 'mag_ratio', 0.54273223646532109, 'sigma', 1.093153)
quasar
('X: ', 2.0005999999999999, 'Y: ', 0.8377, 'mag_ratio', 1.0426624182776467, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(-3.014112059694875, galsim.radians), 'e1', 0.49952780000000002, 'half_light_radius', 0.0)
quasar
('X: ', -0.3301, 'Y: ', -0.2717, 'mag_ratio', 1.7224177371241467, 'sigma', 1.093153)
quasar
('X: ', 0.16750000000000001, 'Y: ', 0.17910000000000001, 'mag_ratio', 0.57277296445840142, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(2.1917408414231794, galsim.radians), 'e1', 0.18289279999999999, 'half_light_radius', 0.0)
**quasar
('X: ', -2.4946999999999999, 'Y: ', -0.1193, 'mag_ratio', 2.6074592463618451, 'sigma', 1.093153)
quasar
('X: ', 0.30780000000000002, 'Y: ', 0.35110000000000002, 'mag_ratio', 0.81794980914263327, 'sigma', 1.093153)
galaxy
('psf', galsim.Gaussian(sigma=1.093153, flux=1.0, gsparams=None), 'phi_angle', galsim.Angle(-0.26941722638532906, galsim.radians), 'e1', 0.7170936, 'half_light_radius', 0.0)** : Traceback (most recent call last):
  File "script.py", line 13, in <module>
    realizer.make_source_catalog(galsim=True, dir='../../../data/source_catalog_galsim.csv')
  File "/Users/Jenny/Desktop/SLRealizer/python/desc/slrealizer/SLRealizer.py", line 143, in make_source_catalog
    data = desc.slrealizer.galsim_generate_data(self.catalog.get_lens(self.catalog.sample[i]['LENSID']), self.observation[j])
  File "/Users/Jenny/Desktop/SLRealizer/python/desc/slrealizer/galsim_null_deblend.py", line 50, in galsim_generate_data
    shape_info = img.FindAdaptiveMom()
  File "/Users/Jenny/anaconda/envs/python2/lib/python2.7/site-packages/galsim/hsm.py", line 561, in FindAdaptiveMom
    hsmparams = hsmparams)
RuntimeError: HSM Error: Error: too many iterations in adaptive moments

**Comment by jennykim1016** [comment]
- So according to this post: \url{https://github.com/GalSim-developers/GalSim/issues/384} there are some galaxies where the adaptive moments do not converge. That seems to be determined by ellipticity. Thus I think we should give up calculating moments with highly elliptical galaxies( roughly if e1>0.5 then we should reject).
- find out why REFF is always zero!
- GALSIM IS MUCH MORE EFFICIENT THEN MY ALGORITHMS 💃 it takes < 30 mins to get 200 by 200 rows in the catalog

**Comment by jennykim1016** [comment]
~ Close the issue : solved the bugs ~
